module NATS
  module IO
    class Error < StandardError
    end

    class ServerError < NATS::IO::Error
    end

    class PermissionViolation < NATS::IO::ServerError
    end

    class MaxSubscriptionsExceeded < NATS::IO::ServerError
    end

    class MaxConnectionsExceeded < NATS::IO::ServerError
    end

    class MaxAccountConnectionsExceeded < NATS::IO::ServerError
    end
    
    class ClientError < NATS::IO::Error
    end

    class ReconnectBufExceeded < NATS::IO::ClientError
    end

    class Disconnected < NATS::IO::ClientError
    end

    class SyncSubRequired < NATS::IO::ClientError
    end

    class BadHeaderMsg < NATS::IO::ClientError
    end

    class MsgNotBound < NATS::IO::ClientError
    end

    class InvalidMsg < TypeError
    end

    class MaxPayload < NATS::IO::ClientError
    end

    class BadQueueName < NATS::IO::ClientError
    end

    class HeadersNotSupported < NATS::IO::ClientError
    end

    class ConnectionReconnecting < NATS::IO::ClientError
    end

    class ConnectError < NATS::IO::Error
    end

    class AuthError < NATS::IO::ConnectError
    end

    class AuthorizationViolation < NATS::IO::AuthError
    end

    class AuthenticationExpired < NATS::IO::AuthError
    end

    class AuthenticationRevoked < NATS::IO::AuthError
    end

    class AccountAuthenticationExpired < NATS::IO::AuthError
    end

    class NoInfoReceived < NATS::IO::ConnectError
    end

    class SecureConnRequired < NATS::IO::ConnectError
    end

    class SecureConnWanted < NATS::IO::ConnectError
    end

    class NoEchoNotSupported < NATS::IO::ConnectError
    end

    class NoServersError < NATS::IO::ConnectError
    end

    class NoRespondersError < NATS::IO::ConnectError
    end

    class StaleConnectionError < NATS::IO::Error
    end

    class Timeout < NATS::IO::Error
    end

    class SocketTimeoutError < NATS::IO::Timeout
    end

    class BadTimeout < NATS::IO::Timeout
    end

    class BadSubject < NATS::IO::Error
    end

    class MsgNoReply < NATS::IO::BadSubject
    end

    class BadSubscription < NATS::IO::Error
    end

    class MaxMessages < NATS::IO::BadSubscription
    end

    class SlowConsumer < NATS::IO::Error
    end

    class ConnectionDrainingError < NATS::IO::Error
    end

    class DrainTimeoutError < NATS::IO::Error
    end
  end

  class Timeout < NATS::IO::Timeout
  end

  class Error < NATS::IO::Error
  end
end
