module NATS
  class KeyValue
    KV_OP: 'KV-Operation'
    KV_DEL: 'DEL'
    KV_PURGE: 'PURGE'
    MSG_ROLLUP_SUBJECT: 'sub'
    MSG_ROLLUP_ALL: 'all'
    ROLLUP: 'Nats-Rollup'
    MARKER_REASON: 'Nats-Marker-Reason'

    VALID_BUCKET_RE: Regexp

    def self.validate_bucket_name: (String?) -> void

    def self.operation_of: (Hash[String, String]?) -> String?

    @name: String
    @stream: String
    @pre: String
    @put_pre: String
    @js: NATS::JetStream
    @direct: bool

    def initialize: (Hash[Symbol, untyped]) -> void

    def get: (String, ?Hash[Symbol, untyped]) -> NATS::KeyValue::Entry

    private def _get: (String, ?Hash[Symbol, untyped]) -> NATS::KeyValue::Entry

    def put: (String, untyped) -> Integer

    def create: (String, untyped, ?Hash[Symbol, untyped]) -> Integer

    EXPECTED_LAST_SUBJECT_SEQUENCE: 'Nats-Expected-Last-Subject-Sequence'

    WRONG_LAST_SEQUENCE_ERR_CODES: Array[Integer]

    def update: (String, untyped, ?Hash[Symbol, untyped]) -> Integer

    private def update_revision: (String, untyped, Integer, (Integer | :never)?) -> Integer

    def delete: (String, ?Hash[Symbol, untyped]) -> Integer

    def purge: (String, ?Hash[Symbol, untyped]) -> NATS::JetStream::PubAck

    PURGE_DELETES_MARKER_THRESHOLD: Integer

    def purge_deletes: (?Hash[Symbol, untyped]) -> nil

    def status: () -> NATS::KeyValue::BucketStatus

    class Entry < Struct[untyped]
    end
  end
end
