module NATS
  class Msg
    attr_reader subject: String
    attr_reader reply: String?
    attr_reader data: String
    attr_reader header: Hash[String, String | Array[String]]?

    def self.add_header_value: (Hash[String, String | Array[String]], String, String) -> (String | Array[String])

    def self.header_lines: (Hash[String, untyped]) -> Array[String]

    include NATS::JetStream::Msg::AckMethods

    def respond: (?String) -> void

    def respond_msg: (NATS::Msg) -> void

    def ==: (untyped) -> bool

    def eql?: (untyped) -> bool

    def hash: () -> Integer

    def size: () -> Integer

    private

    def check_respond!: () -> void

    attr_writer wire_size: Integer?

    def header_values: () -> Hash[String, Array[String]]

    def header_bytesize: () -> Integer
  end
end
