module NATS
  class JetStream
    module API
      class Error < NATS::JetStream::Error::APIError
      end

      class SequenceInfo < Struct[Integer | String]
        def last_active_time: () -> Time?
      end

      class ClusterInfo < Hash[Symbol, untyped]
        def self.decode: (Hash[Symbol, untyped]?) -> NATS::JetStream::API::ClusterInfo?

        def leader_since_time: () -> Time?
      end

      class DesiredClusterInfo < Hash[Symbol, untyped]
        def created_time: () -> Time?
      end

      class PriorityGroupState < Struct[String | Time]
      end

      class ConsumerInfo < Struct[String | NATS::JetStream::API::ConsumerConfig | NATS::JetStream::API::SequenceInfo | Integer | Float | Hash[Symbol, untyped] | Time | bool | Array[NATS::JetStream::API::PriorityGroupState]]
      end

      class ConsumerConfig < Struct[String | Integer | Float | Time | Array[String]]
        def to_json: (*Hash[untyped, untyped]) -> String
      end

      class ConsumerPauseResponse < Struct[bool | Time | Integer | Float]
      end

      class ConsumerResetResponse < Struct[NATS::JetStream::API::ConsumerInfo | Integer]
      end

      module HashAccess
        def []: (Symbol | String | Integer) -> untyped

        def to_h: () -> Hash[Symbol, untyped]

        def self.plain: (untyped) -> untyped

        def self.filter: (Hash[Symbol, untyped], Array[Symbol]) -> Hash[Symbol, untyped]
      end

      class AccountLimits < Struct[Integer | bool]
        include HashAccess
      end

      class APIStats < Struct[Integer]
        include HashAccess
      end

      class Tier < Struct[Integer | NATS::JetStream::API::AccountLimits]
        include HashAccess
      end

      class AccountInfo < Struct[String | Integer | NATS::JetStream::API::AccountLimits | NATS::JetStream::API::APIStats | Hash[String, NATS::JetStream::API::Tier]]
        include HashAccess
      end

      class StreamConfig < Struct[String | Hash[Symbol, untyped] | NATS::JetStream::API::StreamState | bool | Integer]
        def to_json: (*Hash[untyped, untyped]) -> String
      end

      class StreamInfo < Struct[String | Hash[Symbol, untyped] | Array[Hash[Symbol, untyped]] | Time]
      end

      class StreamState < Struct[Integer | String | Array[Integer] | Hash[String, Integer] | NATS::JetStream::API::LostStreamData]
        def first_time: () -> Time?

        def last_time: () -> Time?
      end

      class LostStreamData < Struct[Array[Integer] | Integer]
      end

      class StreamCreateResponse < Struct[String | NATS::JetStream::API::StreamConfig | NATS::JetStream::API::StreamState | bool]
      end

      class StreamPurgeResponse < Struct[bool | Integer]
      end

      class RawStreamMsg < Struct[String | Integer | Hash[String, String | Array[String]] | Time]
        def sequence: () -> Integer
      end
    end
  end
end