module NATS
  class JetStream
    module PullSubscription
      class PubAck < Struct[String | Numeric | bool]
      end

      UNCHECKED_PULL_AGE: Integer

      def self.extended: (NATS::Subscription) -> void

      def next_msg: (untyped) -> void

      def fetch: (Integer, Hash[Symbol, untyped]) ?{ (NATS::Msg) -> void } -> NATS::JetStream::MessageBatch

      def consume: (?Hash[Symbol, untyped]) { (NATS::Msg) -> void } -> NATS::JetStream::ConsumeContext

      def messages: (?Hash[Symbol, untyped]) -> NATS::JetStream::MessagesContext

      def consumer_info: (Hash[Symbol, untyped]) -> NATS::JetStream::ConsumerInfo

      private

      def pull_and_wait: (NATS::JetStream::MessageBatch, Hash[Symbol, untyped], Float, ?Numeric?) ?{ (NATS::Msg) -> void } -> bool?

      def pull_pending: (NATS::JetStream::MessageBatch, Hash[Symbol, untyped], Float) ?{ (NATS::Msg) -> void } -> bool

      def receive: (NATS::JetStream::MessageBatch, Hash[Symbol, untyped], String?, ^() -> NATS::Msg?) ?{ (NATS::Msg) -> void } -> bool

      def take_pending: (NATS::JetStream::MessageBatch, Integer, Integer?) ?{ (NATS::Msg) -> void } -> Integer?

      def release: (NATS::Subscription, Float) -> void

      def hand_over: (NATS::Subscription, ?Float) -> void

      def keep: (NATS::Msg) -> void

      def collect: (NATS::JetStream::MessageBatch, NATS::Msg) ?{ (NATS::Msg) -> void } -> void

      def pull_ended?: (NATS::Msg) -> bool

      def status_error: (NATS::Msg) -> NATS::JetStream::Error

      def pull_expires: (Float) -> Integer

      def wait_pending: (String, Float) -> NATS::Msg?

      def next_pending: (?String?) -> NATS::Msg?

      def next_reply: (NATS::Subscription, Float) -> NATS::Msg?

      def pull: (Hash[Symbol, untyped], String) -> String?

      def pop_pending: () -> NATS::Msg?

      def track_pin: (NATS::Msg) -> NATS::Msg

      def forget_pin: (String?) -> void
    end
  end
end
