language: ruby

rvm:
  - 2.7
  - 3.0.2
  - 3.1.0
  - 3.2.0

cache:
  directories:
  - $HOME/nats-server

before_install:
  - bash ./scripts/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

sudo: required
dist: focal

addons:
  hosts:
    - server-A.clients.nats-service.localhost
    - server-A.clients.fake-nats-service.localhost
    - server-A.routes.nats-service.localhost
    - server-A.routes.fake-nats-service.localhost
    - server-B.clients.nats-service.localhost
    - server-B.clients.fake-nats-service.localhost
    - server-B.routes.nats-service.localhost
    - server-B.routes.fake-nats-service.localhost
    - server-C.clients.nats-service.localhost
    - server-C.clients.fake-nats-service.localhost
    - server-C.routes.nats-service.localhost
    - server-C.routes.fake-nats-service.localhost
