module NATS
  class KeyValue
    class BucketStatus
      attr_reader bucket: String
      attr_reader stream_info: JetStream::API::StreamInfo

      def initialize: (JetStream::API::StreamInfo, String) -> void

      def values: () -> Integer

      def bytes: () -> Integer

      def backing_store: () -> String

      def history: () -> Integer

      def ttl: () -> Float

      def compressed?: () -> bool

      def limit_marker_ttl: () -> Integer

      def metadata: () -> Hash[Symbol, String]?

      def config: () -> NATS::KeyValue::API::KeyValueConfig
    end
  end
end
