module NATS
  class KeyValue
    module Manager
      def key_value: (String, ?Hash[Symbol, untyped]) -> NATS::KeyValue

      def create_key_value: (NATS::KeyValue::API::KeyValueConfig | Hash[Symbol, untyped] | String) -> NATS::KeyValue

      def update_key_value: (NATS::KeyValue::API::KeyValueConfig | Hash[Symbol, untyped]) -> NATS::KeyValue

      def create_or_update_key_value: (NATS::KeyValue::API::KeyValueConfig | Hash[Symbol, untyped]) -> NATS::KeyValue

      def key_value_store_names: () -> Array[String]

      def key_value_stores: () -> Array[NATS::KeyValue::BucketStatus]

      def delete_key_value: (String) -> bool

      private

      def key_value_stream_config: (NATS::KeyValue::API::KeyValueConfig | Hash[Symbol, untyped] | String) -> NATS::JetStream::API::StreamConfig

      def key_value_source: (Hash[Symbol, untyped]) -> Hash[Symbol, untyped]

      def key_value_bucket_source: (Hash[Symbol, untyped], String) -> Hash[Symbol, untyped]

      def config_validate_keys: (NATS::KeyValue::API::KeyValueConfig | Hash[Symbol, untyped] | String) -> bool?

      def key_value_for: (NATS::JetStream::API::StreamConfig, bool?) -> NATS::KeyValue

      def kv_stream_pages: (String) -> Array[untyped]
    end
  end
end
