module NATS
  class Service
    API_PREFIX: String
    ERROR_HEADER: String
    ERROR_CODE_HEADER: String
    DEFAULT_ENDPOINT: String
    PING_RESPONSE_TYPE: String
    INFO_RESPONSE_TYPE: String
    STATS_RESPONSE_TYPE: String

    def self.control_subject: (Symbol | String verb, ?String? name, ?String? id) -> String

    def queue_group_disabled?: () -> bool

    def initialize: (NATS::Client client, Hash[Symbol, untyped] options) ?{ (NATS::Service::Request) -> void } -> void

    def on_error: () { (NATS::Service, NATS::Service::NATSError) -> void } -> void

    def stopped?: () -> bool

    def reset: () -> void

    def ping: () -> Hash[Symbol, untyped]

    def info: () -> Hash[Symbol, untyped]

    def stats: () -> Hash[Symbol, untyped]

    def stop: (?Exception?) -> void
  end

  class Services
    def add: (Hash[Symbol, untyped] options) ?{ (NATS::Service::Request) -> void } -> NATS::Service
  end
end
