module NATS
  class Service
    class Request < NATS::Msg
      def respond: (?String data, ?headers: Hash[String, untyped]?) -> void

      def respond_json: (untyped obj, ?headers: Hash[String, untyped]?) -> void

      def respond_with_error: (Exception | String | Hash[Symbol, untyped] error, ?headers: Hash[String, untyped]?) -> void
    end

    class Endpoint
      attr_reader pending_msgs_limit: Integer?
      attr_reader pending_bytes_limit: Integer?

      def subscription: () -> NATS::Subscription

      def queue_group_disabled?: () -> bool
    end
  end
end
