module NATS
  class Service
    class Request < NATS::Msg
      def respond: (?String data, ?headers: Hash[String, untyped]?) -> void

      def respond_json: (untyped obj, ?headers: Hash[String, untyped]?) -> void

      def respond_with_error: (Exception | String | Hash[Symbol, untyped] error, ?headers: Hash[String, untyped]?) -> void
    end

    class Endpoint
      def subscription: () -> NATS::Subscription
    end
  end
end
