# frozen_string_literal: true

# Checks docs/nq-gap/status.tsv against the repository, so that the status
# of the oracle symbols does not rest on the word of whoever classified
# them. Run from the root of a checkout that has the branch's history:
#
#   ruby docs/nq-gap/verify_status.rb          # check, exit 1 on a problem
#   ruby docs/nq-gap/verify_status.rb --map    # also write commits.md
#
# It checks that:
# - every one of the oracle symbols of inventory.tsv has one row, with a
#   known status, and that none is left missing or partial;
# - every row that was missing or partial at the audit and is present now
#   names the commit that closed it, and that commit is on the branch,
#   after the audited revision;
# - every file and line that a row points to exists;
# - the commit of each such row changes a file that the row points to, so
#   that the commit and the code it names agree;
# - every deliberate row says where its difference is documented.

require "csv"
require "set"

AUDITED = "1b4cf34"
DIR = File.expand_path(__dir__)
STATUSES = %w[present deliberate n/a partial missing].freeze

def tsv(name)
  CSV.read(File.join(DIR, name), col_sep: "\t", headers: true, quote_char: "\u0000", encoding: "UTF-8")
end

def git(*args)
  IO.popen(["git", *args], &:read).force_encoding("UTF-8")
end

problems = []
inventory = tsv("inventory.tsv")
rows = tsv("status.tsv")

symbols = rows.map { |r| r["oracle_symbol"] }
problems << "status.tsv has #{rows.size} rows, inventory.tsv #{inventory.size}" if rows.size != inventory.size
missing_rows = inventory.map { |r| r["oracle_symbol"] } - symbols
problems << "symbols without a status: #{missing_rows.first(5).join(", ")}" unless missing_rows.empty?
dups = symbols.tally.select { |_, n| n > 1 }.keys
problems << "symbols with more than one status: #{dups.first(5).join(", ")}" unless dups.empty?

commits = git("log", "--format=%H", "#{AUDITED}..HEAD").split
files_of = Hash.new { |h, c| h[c] = git("show", "--name-only", "--format=", c).split.to_set }
resolve = ->(ref) { commits.find { |c| c.start_with?(ref) } }

by_commit = Hash.new { |h, c| h[c] = [] }
rows.each do |r|
  sym = r["oracle_symbol"]
  status = r["current_status"]
  problems << "#{sym}: unknown status #{status.inspect}" unless STATUSES.include?(status)
  problems << "#{sym}: still #{status}" if %w[missing partial].include?(status)

  locs = r["location"].to_s.scan(%r{((?:lib|sig|spec)/[\w./-]+\.rbs?)(?::(\d+))?})
  locs.each do |file, line|
    if !File.exist?(file)
      problems << "#{sym}: #{file} does not exist"
    elsif line && line.to_i > File.foreach(file).count
      problems << "#{sym}: #{file}:#{line} is past the end of the file"
    end
  end

  refs = r["commit"].to_s.split(/[\s,;\/+]+/).reject(&:empty?)
  shas = refs.map { |ref| resolve.call(ref) || (problems << "#{sym}: commit #{ref} is not on the branch" && nil) }.compact
  shas.each { |c| by_commit[c] << sym }

  closed = %w[missing partial].include?(r["audited_status"]) && status == "present"
  problems << "#{sym}: closed since the audit, but names no commit" if closed && shas.empty?
  if closed && !shas.empty? && !locs.empty?
    touched = shas.map { |c| files_of[c] }.reduce(:|)
    names = r["location"].scan(%r{[\w./-]+\.rbs?}).map { |f| File.basename(f) }
    unless touched.any? { |f| names.include?(File.basename(f)) }
      problems << "#{sym}: commit #{refs.join(" ")} changes none of #{names.uniq.join(", ")}"
    end
  end

  if status == "deliberate" && r["note"].to_s !~ /CHANGELOG|README|commit|server|nats-server/i
    problems << "#{sym}: deliberate, but the note does not say where that is documented"
  end
end

counts = rows.map { |r| r["current_status"] }.tally
puts "symbols: #{rows.size}  " + STATUSES.map { |s| "#{s}: #{counts.fetch(s, 0)}" }.join("  ")
puts "commits that closed symbols: #{by_commit.size}"

if ARGV.include?("--map")
  subjects = commits.to_h { |c| [c, git("log", "-1", "--format=%s", c).strip] }
  File.open(File.join(DIR, "commits.md"), "w:UTF-8") do |f|
    f.puts "# Commits and the oracle symbols they closed"
    f.puts
    f.puts "Generated by `ruby docs/nq-gap/verify_status.rb --map` from status.tsv."
    f.puts "Each commit closes one feature or fix; the symbols are those of the"
    f.puts "oracle that it made present."
    f.puts
    commits.reverse_each do |c|
      next unless by_commit.key?(c)

      f.puts "- `#{c[0, 7]}` #{subjects[c]} (#{by_commit[c].size}): #{by_commit[c].map { |s| "`#{s}`" }.join(", ")}"
    end
    others = commits.reverse.reject { |c| by_commit.key?(c) }
    f.puts
    f.puts "Commits that close no oracle symbol of their own (docs, spec fixes, and"
    f.puts "features whose symbols were partly present at the audit):"
    f.puts
    others.each { |c| f.puts "- `#{c[0, 7]}` #{subjects[c]}" }
  end
  puts "wrote #{File.join(DIR, "commits.md")}"
end

if problems.empty?
  puts "OK"
else
  puts problems
  exit 1
end
